CREATE TABLE IF NOT EXISTS Article (
  FeatureID INTEGER UNSIGNED NOT NULL,
  Article TEXT NULL,
  PRIMARY KEY(FeatureID),
  FULLTEXT INDEX Fulltext_Article_Article(Article)
);

CREATE TABLE IF NOT EXISTS Feature (
  FeatureID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  UserID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Title VARCHAR(100) NULL,
  Description VARCHAR(255) NULL,
  StartTime TIMESTAMP NULL,
  StopTime TIMESTAMP NULL,
  Type VARCHAR(100) NULL,
  LastUpdate TIMESTAMP,
  CreateTime TIMESTAMP,
  PRIMARY KEY(FeatureID)
);

CREATE TABLE IF NOT EXISTS FeaturePosition (
  FeatureID INTEGER UNSIGNED NOT NULL,
  PositionID INTEGER UNSIGNED NOT NULL,
  Weight INTEGER UNSIGNED DEFAULT 1,
  UNIQUE INDEX Unique_FeaturePosition(FeatureID, PositionID)
);

CREATE TABLE IF NOT EXISTS Gallery (
  FeatureID INTEGER UNSIGNED NOT NULL,
  ImageDir VARCHAR(255) NULL,
  ThumbWidth INTEGER UNSIGNED NULL,
  ThumbHeight INTEGER UNSIGNED NULL,
  ImageStyle ENUM('popup', 'inline') NOT NULL DEFAULT 'popup',
  PRIMARY KEY(FeatureID)
);

CREATE TABLE IF NOT EXISTS GalleryImage (
  ImageID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FeatureID INTEGER UNSIGNED NOT NULL,
  FileName VARCHAR(45) NOT NULL,
  Title VARCHAR(100) NULL,
  Description VARCHAR(255) NULL,
  Sequence INTEGER UNSIGNED NULL,
  PRIMARY KEY (ImageID)
);

CREATE TABLE IF NOT EXISTS Poll (
  FeatureID INTEGER UNSIGNED NOT NULL,
  Question VARCHAR(255) NULL,
  PRIMARY KEY(FeatureID)
);

CREATE TABLE IF NOT EXISTS PollChoice (
  ChoiceID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FeatureID INTEGER UNSIGNED NOT NULL,
  Choice VARCHAR(255) NULL,
  PRIMARY KEY(ChoiceID)
);

CREATE TABLE IF NOT EXISTS PollResponse (
  ChoiceID INTEGER UNSIGNED NOT NULL,
  FeatureID INTEGER UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Position (
  PositionID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  PRIMARY KEY(PositionID),
  UNIQUE INDEX Unique_Position(Name)
);

CREATE TABLE IF NOT EXISTS Review (
  FeatureID INTEGER UNSIGNED NOT NULL,
  Rating INTEGER UNSIGNED NULL,
  Genre VARCHAR(255) NULL,
  Review TEXT NULL,
  PRIMARY KEY(FeatureID),
  FULLTEXT INDEX Fulltext_Review_Review(Review)
);

CREATE TABLE IF NOT EXISTS Settings (
  Type VARCHAR(255) NULL,
  Data TEXT NULL,
  PRIMARY KEY(Type)
);

CREATE TABLE IF NOT EXISTS Template (
  Uri VARCHAR(255) NOT NULL,
  TemplateText TEXT NULL
);