GRANT USAGE ON *.* TO 'limbonia'@'localhost' IDENTIFIED BY '40two';
GRANT ALL PRIVILEGES ON `limbonia`.* TO 'limbonia'@'localhost';

CREATE DATABASE IF NOT EXISTS `limbonia`;
USE limbonia;

CREATE TABLE IF NOT EXISTS ResourceKey (
  KeyID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(25) NOT NULL,
  PRIMARY KEY(KeyID),
  UNIQUE INDEX Unique_ResourceName(Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO ResourceKey (Name) VALUES ('Admin');

CREATE TABLE IF NOT EXISTS ResourceLock (
  LockID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  KeyID INTEGER UNSIGNED NOT NULL,
  MinKey INTEGER UNSIGNED NOT NULL DEFAULT 1000,
  Resource VARCHAR(255) NULL,
  Component VARCHAR(255) NULL,
  PRIMARY KEY(LockID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Role` (
  RoleID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Description text,
  PRIMARY KEY (RoleID),
  UNIQUE INDEX Unique_RoleName (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO Role (Name, Description) VALUES ('Admin', 'This is the main administrator role, a user with this has access to everything!');

CREATE TABLE IF NOT EXISTS Role_Key (
  RoleID INTEGER UNSIGNED NOT NULL,
  KeyID INTEGER UNSIGNED NOT NULL,
  Level INTEGER UNSIGNED NOT NULL DEFAULT 0,
  INDEX Unique_RoleKey(RoleID, KeyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO Role_Key (RoleID, KeyID, `Level`) VALUES ((SELECT r.RoleID FROM Role r WHERE r.Name = 'Admin'), (SELECT r.KeyID FROM ResourceKey r WHERE r.Name = 'Admin'), 1000);

CREATE TABLE IF NOT EXISTS Settings (
  Type VARCHAR(255) NOT NULL,
  Data TEXT NULL,
  PRIMARY KEY(Type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS User (
  UserID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Type ENUM('internal','contact','system') NOT NULL DEFAULT 'internal',
  Email VARCHAR(255) NOT NULL,
  FirstName VARCHAR(50) NULL,
  LastName VARCHAR(50) NULL,
  Position VARCHAR(100) NULL,
  Notes mediumtext,
  StreetAddress VARCHAR(255) NULL,
  ShippingAddress VARCHAR(255) NULL,
  City VARCHAR(50) NULL,
  State VARCHAR(2) NULL,
  Zip VARCHAR(9) NOT NULL DEFAULT '000000000',
  Country VARCHAR(50) NULL,
  WorkPhone VARCHAR(25) NULL,
  HomePhone VARCHAR(25) NULL,
  CellPhone VARCHAR(25) NULL,
  Active TINYINT(1) NOT NULL DEFAULT 1,
  Visible TINYINT(1) NOT NULL DEFAULT 1,
  Password VARCHAR(255) BINARY NOT NULL DEFAULT '',
  PRIMARY KEY (UserID),
  UNIQUE INDEX Unique_Email (Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS User_Role (
  UserID INTEGER UNSIGNED NOT NULL,
  RoleID INTEGER UNSIGNED NOT NULL,
  INDEX Unique_UserRole(UserID, RoleID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS UserAuth (
  UserID INTEGER UNSIGNED NOT NULL,
  AuthToken VARCHAR(255) NOT NULL,
  LastUseTime TIMESTAMP NOT NULL,
  INDEX Unique_UserAuth(UserID, AuthToken)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO User (Email, FirstName, LastName, Visible) VALUES ('MasterAdmin', 'Master', 'Admin', 0);
INSERT INTO User_Role (RoleID, UserID) VALUES ((SELECT r.RoleID FROM Role r WHERE r.Name = 'Admin'), (SELECT u.UserID FROM `User` u WHERE u.Email = 'MasterAdmin'));
